### ISSUE TITLE
Use drive brake mode for autonomous 

### ISSUE THREAD

**Issue by jwt388** [ToughTechs151/Crescendo2024#76]
We should set the drive motors to brake mode when entering Autonomous mode to get more accurate movements. Set back to coast mode when entering Teleop mode.

**Comment by jwt388** [comment]
Robot.java has autonomousInit and teleopInit functions that are run when entering each mode so the code can be added there. The drive already has the setBrakeMode function. In Robot you will have to call a function in RobotContainer to get the drive subsystem so you can access its public functions.

**Comment by kcq888** [comment]
You should consider using PID for this even though if we are not using trajectories. Trajectory uses odometry to stop at the exact location. We have only 1 week before week 3 competition, maybe brake mode on the motors might be the shortest path.
